title: Valence
description: A private, controlled, curated AI space.
url: https://helixailabs.github.io
baseurl: /Valence
defaults:
  - scope: { path: "" }
    values: { layout: default }
  - scope: { path: "", type: posts }
    values: { layout: post, category: release }
